"use client";

import { useParams } from "next/navigation";
import { useEffect, useState } from "react";

type Variant = { id: number; sku: string; title: string; size: string | null; color: string | null; price: number; salePrice: number | null; status: string; available: number };
type StoreData = { store: { id: number; name: string; tagline: string | null; description: string | null; logoUrl: string | null; bannerUrl: string | null; category: string; contactOptions: Record<string, string>; fulfillmentMethods: string[]; policies: Record<string, string> }; branches: { id: number; name: string; address: string; city: string; pickupEnabled: boolean; deliveryEnabled: boolean }[]; promotions: { id: number; title: string; description: string | null }[]; products: { id: number; name: string; collection: string | null; brand: string | null; description: string; imageUrl: string | null; variants: Variant[] }[] };

export default function StorefrontPage() {
  const { slug } = useParams<{ slug: string }>(); const [data, setData] = useState<StoreData | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { fetch(`/api/stores/${encodeURIComponent(slug)}`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); return body; }).then(setData).catch((reason) => setError(reason.message ?? "Store unavailable.")); }, [slug]);
  if (error) return <main className="storefront-state"><a href="/" className="brand"><span>Neuro</span><strong>City</strong></a><h1>Store unavailable</h1><p>{error}</p><a href="/">Return to NeuroCity</a></main>;
  if (!data) return <main className="storefront-state"><p>Loading storefront…</p></main>;
  const { store } = data;
  async function accountAction(body: object) { const response = await fetch("/api/account", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); if (response.status === 401) return window.location.href = `/login?return_to=${encodeURIComponent(`/stores/${slug}`)}`; const result = await response.json(); setNotice(response.ok ? "Saved to your NeuroCity account." : result.error); }
  return <main className="real-storefront"><header><a href="/" className="brand"><span>Neuro</span><strong>City</strong></a><nav><a href="#catalogue">Catalogue</a><a href="#store-info">Store information</a><button onClick={() => accountAction({ action: "store", merchantId: store.id })}>Save store</button><a href="/account">Account</a></nav></header>{notice && <button className="store-notice" onClick={() => setNotice("")}>{notice} ×</button>}<section className="real-store-hero"><div><p className="eyebrow">{store.category} · Windhoek</p>{store.logoUrl && <img src={store.logoUrl} alt={`${store.name} logo`} />}<h1>{store.name}</h1><h2>{store.tagline}</h2><p>{store.description}</p><div>{store.fulfillmentMethods?.map((method) => <span key={method}>{method.replaceAll("_", " ")}</span>)}</div></div>{store.bannerUrl && <img src={store.bannerUrl} alt={`${store.name} storefront banner`} />}</section>{data.promotions.length > 0 && <section className="store-promotions">{data.promotions.map((promotion) => <article key={promotion.id}><strong>{promotion.title}</strong><span>{promotion.description}</span></article>)}</section>}<section className="real-catalogue" id="catalogue"><div className="section-heading"><div><p className="eyebrow">Shop {store.name}</p><h2>Catalogue</h2></div><p>Select a size and colour to see variant-level availability.</p></div><div className="real-product-grid">{data.products.map((product) => <StoreProduct key={product.id} product={product} accountAction={accountAction} />)}</div></section><section className="store-information" id="store-info"><div><p className="eyebrow">Visit or contact</p><h2>Store information</h2></div><div>{data.branches.map((branch) => <article key={branch.id}><h3>{branch.name}</h3><p>{branch.address}</p><span>{branch.pickupEnabled ? "Pickup available" : "No pickup"}</span><span>{branch.deliveryEnabled ? "Delivery available" : "No delivery"}</span></article>)}</div><div className="store-policy"><h3>Store policies</h3>{Object.entries(store.policies ?? {}).map(([name, policy]) => <p key={name}><strong>{name.replaceAll("_", " ")}</strong>{policy}</p>)}</div></section></main>;
}

function StoreProduct({ product, accountAction }: { product: StoreData["products"][number]; accountAction: (body: object) => void }) { const [variantId, setVariantId] = useState(product.variants[0]?.id ?? 0); const variant = product.variants.find((item) => item.id === variantId); return <article className="real-product-card"><div>{product.imageUrl && <img src={product.imageUrl} alt={product.name} />}<button className="save-product" onClick={() => accountAction({ action: "wishlist", productId: product.id })}>♡</button></div><small>{product.brand ?? "Local brand"}{product.collection ? ` · ${product.collection}` : ""}</small><h3>{product.name}</h3><p>{product.description}</p>{product.variants.length > 0 ? <><label>Variant<select value={variantId} onChange={(event) => setVariantId(Number(event.target.value))}>{product.variants.map((item) => <option key={item.id} value={item.id}>{[item.size, item.color].filter(Boolean).join(" / ") || item.title}</option>)}</select></label><div className="variant-purchase"><span><strong>N${(variant?.salePrice ?? variant?.price ?? 0).toFixed(2)}</strong><small>SKU {variant?.sku}</small></span><button disabled={!variant || variant.available < 1} onClick={() => variant && accountAction({ action: "cart", variantId: variant.id, quantity: 1 })}>{variant && variant.available > 0 ? `Add · ${variant.available} available` : "Ask store"}</button></div></> : <p>Variants being prepared by the merchant.</p>}</article>; }
