"use client";

import { FormEvent, useEffect, useState } from "react";

type Document = { id: number; documentType: string; status: string; originalName: string | null; viewUrl: string | null };
type Application = { id: number; reference: string; status: string; tradingName: string; legalName: string; category: string; representativeName: string; email: string; phone: string; description: string; submittedAt: string; documents?: Document[] };
type Merchant = { id: number; name: string; category: string; status: string; contactName: string | null; contactEmail: string | null; createdAt: string };

export default function AdminPage() {
  const [items, setItems] = useState<Application[] | null>(null); const [merchants, setMerchants] = useState<Merchant[]>([]);
  const [auth, setAuth] = useState({ name: "Sergej Witbooi", email: "sergejwitbooi@gmail.com", password: "" }); const [mode, setMode] = useState<"login" | "register">("register"); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/admin/applications"); if (!response.ok) return setItems(null); const data = await response.json(); setItems(data.applications); setMerchants(data.merchants ?? []); }
  useEffect(() => { load(); }, []);
  async function authenticate(event: FormEvent) { event.preventDefault(); const response = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(auth) }); const data = await response.json(); if (!response.ok) return setMessage(data.error); setMessage(""); await load(); }
  async function review(id: number, status: string) { const notes = window.prompt("Optional review note") ?? ""; const response = await fetch("/api/admin/applications", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status, notes }) }); const data = await response.json(); setMessage(response.ok ? `Application moved to ${status.replaceAll("_", " ")}.` : data.error); if (response.ok) await load(); }
  async function changeMerchant(merchant: Merchant, status: "active" | "suspended" | "removed") { if (status === "removed" && !window.confirm(`Remove ${merchant.name} from NeuroCity? Their storefront and all dashboard access will be disabled. Records will be retained.`)) return; const reason = status === "active" ? (window.prompt("Optional reactivation note") ?? "") : (window.prompt(`Reason for ${status === "suspended" ? "suspension" : "removal"} (required)`) ?? ""); if (status !== "active" && !reason.trim()) return setMessage("A reason is required."); const response = await fetch("/api/admin/merchants", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ merchantId: merchant.id, status, reason, confirmation: status === "removed" ? "REMOVE" : undefined }) }); const data = await response.json(); setMessage(response.ok ? `${merchant.name} is now ${status}.` : data.error); if (response.ok) await load(); }

  if (!items) return <main className="admin-auth"><a href="/" className="brand"><span>Neuro</span><strong>City</strong></a><form onSubmit={authenticate}><p className="eyebrow">NeuroCity administration</p><h1>{mode === "register" ? "Create the first administrator" : "Administrator login"}</h1>{mode === "register" && <label>Full name<input value={auth.name} onChange={(e) => setAuth({ ...auth, name: e.target.value })} /></label>}<label>Email<input type="email" value={auth.email} onChange={(e) => setAuth({ ...auth, email: e.target.value })} /></label><label>Password<input type="password" minLength={10} value={auth.password} onChange={(e) => setAuth({ ...auth, password: e.target.value })} /></label>{message && <p className="form-error">{message}</p>}<button>{mode === "register" ? "Create administrator" : "Sign in"}</button><button type="button" className="switch-auth" onClick={() => setMode(mode === "register" ? "login" : "register")}>{mode === "register" ? "I already have an account" : "Create the first administrator"}</button></form></main>;

  return <main className="admin-page"><header><div><p className="eyebrow">NeuroCity operations</p><h1>Merchant administration</h1></div><a href="/">View mall</a></header>{message && <button className="workspace-message" onClick={() => setMessage("")}>{message} ×</button>}
    <section className="merchant-management"><div><p className="eyebrow">Approved merchants</p><h2>Account lifecycle</h2><p>Suspend access temporarily, remove a merchant while retaining records, or reactivate an account.</p></div>{merchants.length === 0 ? <p>No merchant workspaces yet.</p> : merchants.map((merchant) => <article key={merchant.id}><div><strong>{merchant.name}</strong><span>{merchant.category}</span></div><span className={`merchant-status status-${merchant.status}`}>{merchant.status}</span><div className="merchant-actions">{merchant.status !== "active" && merchant.status !== "pilot" && <button className="approve" onClick={() => changeMerchant(merchant, "active")}>Reactivate</button>}{merchant.status !== "suspended" && merchant.status !== "removed" && <button onClick={() => changeMerchant(merchant, "suspended")}>Suspend</button>}{merchant.status !== "removed" && <button className="reject" onClick={() => changeMerchant(merchant, "removed")}>Remove</button>}</div></article>)}</section>
    <div className="admin-section-heading"><p className="eyebrow">Applications</p><h2>Merchant applications</h2></div><section className="admin-applications">{items.length === 0 ? <div className="empty-state"><h2>No applications yet</h2></div> : items.map((item) => <article key={item.id}><header><div><small>{item.reference}</small><h2>{item.tradingName}</h2><p>{item.legalName} · {item.category}</p></div><span>{item.status.replaceAll("_", " ")}</span></header><p>{item.description}</p><dl><div><dt>Representative</dt><dd>{item.representativeName}</dd></div><div><dt>Contact</dt><dd>{item.email}<br />{item.phone}</dd></div><div><dt>Submitted</dt><dd>{new Date(item.submittedAt).toLocaleDateString("en-NA")}</dd></div></dl><div className="admin-documents">{item.documents?.map((document) => document.viewUrl ? <a key={document.id} href={document.viewUrl} target="_blank" rel="noreferrer">{document.documentType.replaceAll("_", " ")} ✓</a> : <span key={document.id}>{document.documentType.replaceAll("_", " ")} · {document.status.replaceAll("_", " ")}</span>)}</div><footer><button onClick={() => review(item.id, "under_review")}>Start review</button><button onClick={() => review(item.id, "more_information_required")}>Request information</button><button className="approve" onClick={() => review(item.id, "approved")}>Approve</button><button className="reject" onClick={() => review(item.id, "rejected")}>Reject</button></footer></article>)}</section>
  </main>;
}
