"use client";

import { useCallback, useEffect, useState } from "react";

type Tab = "Overview" | "Setup" | "Orders" | "Products" | "Inventory";
type Product = { id: number; name: string; sku: string; price: number | null; status: string; imageUrl: string };
type Stock = { productId: number; productName: string; sku: string; branch: string; onHand: number | null; reserved: number | null; safetyStock: number | null; available: number | null };
type Order = { id: number; reference: string; status: string; total: number; fulfillmentMethod: string; paymentMethod: string; createdAt: string; allowedTransitions: string[]; items: { id: number; productName: string; quantity: number }[] };
type Session = { authenticated: boolean; user?: { displayName: string; email: string }; memberships: { role: string; merchantId: number }[]; canBootstrap: boolean };
type Merchant = { name: string; category: string; contactName: string | null; contactEmail: string | null; contactPhone: string | null; website: string | null; pickupLocation: string | null; deliveryMode: string; setupStep: number };
const pretty = (value: string) => value.replaceAll("_", " ");
const money = (value: number | null) => value === null ? "Not set" : `N$${value.toFixed(2)}`;

export default function MerchantWorkspace({ onPreview }: { onPreview: () => void }) {
  const [tab, setTab] = useState<Tab>("Setup");
  const [products, setProducts] = useState<Product[]>([]);
  const [stock, setStock] = useState<Stock[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);
  const [stats, setStats] = useState({ products: 0, publishedProducts: 0, orders: 0, readiness: 42 });
  const [message, setMessage] = useState("");
  const [session, setSession] = useState<Session | null>(null);
  const [merchant, setMerchant] = useState<Merchant | null>(null);
  const [claimCode, setClaimCode] = useState("");
  const [inviteEmail, setInviteEmail] = useState("");
  const [inviteCode, setInviteCode] = useState("");
  const load = useCallback(async () => {
    const responses = await Promise.all([fetch("/api/merchant/overview"), fetch("/api/merchant/products"), fetch("/api/merchant/inventory"), fetch("/api/merchant/orders")]);
    if (!responses.every((response) => response.ok)) throw new Error("Merchant workspace could not be loaded.");
    const [overview, productData, stockData, orderData] = await Promise.all(responses.map((response) => response.json()));
    setStats(overview); setProducts(productData.products); setStock(stockData.inventory); setOrders(orderData.orders);
  }, []);
  const loadSession = useCallback(async () => { const response = await fetch("/api/merchant/session"); const data = await response.json(); setSession(data); if (response.ok && data.memberships?.length) { await load(); const setup = await fetch("/api/merchant/setup"); if (setup.ok) setMerchant((await setup.json()).merchant); } }, [load]);
  useEffect(() => { loadSession().catch((error) => setMessage(error.message)); }, [loadSession]);
  async function patch(url: string, body: object, success: string) { const response = await fetch(url, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) return setMessage(data.error); setMessage(success); await load(); }
  async function postAccess(url: string, body: object = {}) { const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) return setMessage(data.error); setMessage("Merchant workspace access confirmed."); await loadSession(); }
  async function createInvite() { const response = await fetch("/api/merchant/invitations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: inviteEmail, role: "manager" }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error); setInviteCode(data.code); setMessage("Invitation created. Copy the one-time code now."); }
  async function saveSetup() { if (!merchant) return; const response = await fetch("/api/merchant/setup", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(merchant) }); const data = await response.json(); if (!response.ok) return setMessage(data.error); setMerchant(data.merchant); setMessage("Merchant setup saved."); }

  if (!session) return <section className="access-card"><h2>Opening secure merchant workspace…</h2></section>;
  if (!session.authenticated) return <section className="access-card"><p className="eyebrow">Secure merchant login</p><h2>Sign in to manage your NeuroCity store</h2><p>Use the account that received your NeuroCity invitation. The hosted site verifies your identity before any merchant data is returned.</p></section>;
  if (!session.memberships?.length) return <section className="access-card"><p className="eyebrow">Merchant access</p><h2>Welcome, {session.user?.displayName}</h2><p>Enter the one-time invitation code supplied by NeuroCity. Codes are email-bound and expire after seven days.</p><label>Invitation code<input value={claimCode} onChange={(e) => setClaimCode(e.target.value.toUpperCase())} /></label><button onClick={() => postAccess("/api/merchant/claim", { code: claimCode })}>Join merchant workspace</button>{session.canBootstrap && <button className="secondary" onClick={() => postAccess("/api/merchant/bootstrap")}>Activate first LightWork owner</button>}{message && <p>{message}</p>}</section>;
  return <section className="dashboard-shell"><aside><div className="merchant-mark"><img src="/lightwork-logo.png" alt="" /><div><b>LightWork</b><span>Pilot workspace</span></div></div>{(["Overview", "Orders", "Products", "Inventory"] as Tab[]).map((item) => <button className={tab === item ? "active" : ""} key={item} onClick={() => setTab(item)}>{item}<span>{item === "Products" ? products.length : item === "Orders" ? orders.length : ""}</span></button>)}<button onClick={onPreview}>Storefront <span>↗</span></button><div className="pilot-status"><span /><b>Pilot setup</b><small>{stats.readiness}% complete</small></div></aside>
    <div className="dashboard-main"><div className="dashboard-head"><div><p className="eyebrow">Merchant {tab.toLowerCase()}</p><h1>{tab === "Overview" ? `Welcome, ${session.user?.displayName}.` : tab}</h1><p>Signed in as {session.user?.email} · {session.memberships[0].role}</p></div><button onClick={onPreview}>Preview storefront ↗</button></div>{message && <button className="workspace-message" onClick={() => setMessage("")}>{message} ×</button>}
      {tab === "Overview" && <><div className="metric-grid"><Metric label="Published products" value={String(stats.publishedProducts)} note={`${stats.products - stats.publishedProducts} need confirmation`} /><Metric label="Orders recorded" value={String(stats.orders)} note="Persistent pilot orders" /><Metric label="Store readiness" value={`${stats.readiness}%`} note="Complete catalogue and policies" /><Metric label="Available units" value={String(stock.reduce((sum, row) => sum + (row.available ?? 0), 0))} note="After safety stock" /></div><div className="ops-callout"><h3>Safe publication workflow</h3><p>Confirm the current name and price, select Published, tick the merchant confirmation box, then save. Unconfirmed artwork remains unavailable to customers.</p></div></>}
      {tab === "Setup" && merchant && <div className="setup-form"><div className="setup-progress"><b>Merchant setup</b><span>Account secured ✓ · Business details ✓ · Catalogue next</span></div><label>Business name<input value={merchant.name} onChange={(e) => setMerchant({ ...merchant, name: e.target.value })} /></label><label>Category<input value={merchant.category} onChange={(e) => setMerchant({ ...merchant, category: e.target.value })} /></label><label>Contact person<input value={merchant.contactName ?? ""} onChange={(e) => setMerchant({ ...merchant, contactName: e.target.value })} /></label><label>Contact email<input type="email" value={merchant.contactEmail ?? ""} onChange={(e) => setMerchant({ ...merchant, contactEmail: e.target.value })} /></label><label>Phone<input value={merchant.contactPhone ?? ""} onChange={(e) => setMerchant({ ...merchant, contactPhone: e.target.value })} /></label><label>Website<input value={merchant.website ?? ""} onChange={(e) => setMerchant({ ...merchant, website: e.target.value })} /></label><label className="wide">Pickup location<input value={merchant.pickupLocation ?? ""} onChange={(e) => setMerchant({ ...merchant, pickupLocation: e.target.value })} /></label><label>Delivery<select value={merchant.deliveryMode} onChange={(e) => setMerchant({ ...merchant, deliveryMode: e.target.value })}><option value="merchant_managed">Merchant managed</option><option value="platform_managed">NeuroCity managed</option></select></label><button onClick={saveSetup}>Save setup</button>{session.memberships[0].role === "owner" && <div className="invite-panel"><h3>Invite a dashboard manager</h3><p>They must sign in with this exact email, then enter the one-time code.</p><input type="email" placeholder="manager@example.com" value={inviteEmail} onChange={(e) => setInviteEmail(e.target.value)} /><button onClick={createInvite}>Create 7-day invitation</button>{inviteCode && <code>{inviteCode}</code>}</div>}</div>}
      {tab === "Products" && <div className="ops-list">{products.map((product) => <ProductEditor key={product.id} product={product} onChange={(next) => setProducts((rows) => rows.map((row) => row.id === next.id ? next : row))} onSave={(confirmed) => patch("/api/merchant/products", { id: product.id, name: product.name, price: product.price, status: product.status, merchantConfirmed: confirmed }, `${product.name} saved.`)} />)}</div>}
      {tab === "Inventory" && <div className="ops-list">{stock.map((row) => <article className="ops-row" key={row.productId}><div className="ops-title"><b>{row.productName}</b><small>{row.sku} · {row.branch}</small></div><label>On hand<input type="number" min="0" value={row.onHand ?? ""} onChange={(e) => setStock((rows) => rows.map((item) => item.productId === row.productId ? { ...item, onHand: e.target.value === "" ? null : Number(e.target.value) } : item))} /></label><label>Safety stock<input type="number" min="0" value={row.safetyStock ?? 0} onChange={(e) => setStock((rows) => rows.map((item) => item.productId === row.productId ? { ...item, safetyStock: Number(e.target.value) } : item))} /></label><div className="stock-number"><small>Available</small><b>{row.onHand === null ? "—" : Math.max(0, row.onHand - (row.reserved ?? 0) - (row.safetyStock ?? 0))}</b></div><button onClick={() => patch("/api/merchant/inventory", { productId: row.productId, onHand: row.onHand, safetyStock: row.safetyStock ?? 0 }, `${row.productName} inventory saved.`)}>Save stock</button></article>)}</div>}
      {tab === "Orders" && <div className="ops-list">{orders.length === 0 ? <div className="empty-state"><h3>No orders yet</h3><p>Published products and private pilot checkout orders will appear here.</p></div> : orders.map((order) => <article className="order-card" key={order.id}><header><div><b>{order.reference}</b><small>{new Date(order.createdAt).toLocaleString("en-NA")}</small></div><span>{pretty(order.status)}</span></header><p>{order.items.map((item) => `${item.quantity}× ${item.productName}`).join(", ")}</p><div className="order-meta"><span>{pretty(order.fulfillmentMethod)}</span><span>{pretty(order.paymentMethod)}</span><b>{money(order.total)}</b></div><footer>{order.allowedTransitions.map((next) => <button key={next} onClick={() => patch("/api/merchant/orders", { orderId: order.id, status: next }, `Order moved to ${pretty(next)}.`)}>{pretty(next)}</button>)}</footer></article>)}</div>}
    </div></section>;
}
function ProductEditor({ product, onChange, onSave }: { product: Product; onChange: (product: Product) => void; onSave: (confirmed: boolean) => void }) { const [confirmed, setConfirmed] = useState(false); return <article className="ops-row product-editor"><img src={product.imageUrl} alt="" /><label>Name<input value={product.name} onChange={(e) => onChange({ ...product, name: e.target.value })} /></label><label>Current price<input type="number" min="0" step="0.01" value={product.price ?? ""} onChange={(e) => onChange({ ...product, price: e.target.value === "" ? null : Number(e.target.value) })} /></label><label>Status<select value={product.status} onChange={(e) => onChange({ ...product, status: e.target.value })}><option value="needs_confirmation">Needs confirmation</option><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label className="confirm-check"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} /> Merchant confirms current details</label><button onClick={() => onSave(confirmed)}>Save product</button></article>; }
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <article className="metric"><span>{label}</span><b>{value}</b><small>{note}</small></article>; }
