"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type Match = { id: number; name: string; collection: string | null; price: number | null; imageUrl: string | null; availableUnits: number; colours: string[]; sizes: string[]; store: { name: string; slug: string } };
type Message = { id: string; role: "user" | "neuro"; text: string; matches?: Match[] };
const prompts = ["Black hoodies under N$1,500", "A complete outfit under N$2,000", "A birthday gift under N$800"];
const money = (value: number | null) => value === null ? "Ask store for price" : `N$${new Intl.NumberFormat("en-NA", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value)}`;

export function NeuroConcierge({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [input, setInput] = useState(""); const [busy, setBusy] = useState(false);
  const [messages, setMessages] = useState<Message[]>([{ id: "welcome", role: "neuro", text: "Hi, I’m Neuro. Tell me what you need, your preferred colour or size, and your budget. I’ll search products that merchants have actually published." }]);
  const endRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (open) endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [open, messages, busy]);
  if (!open) return null;
  async function ask(message: string) { const text = message.trim(); if (!text || busy) return; setMessages((current) => [...current, { id: crypto.randomUUID(), role: "user", text }]); setInput(""); setBusy(true); try { const response = await fetch("/api/concierge", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ message: text }) }); const result = await response.json(); setMessages((current) => [...current, { id: crypto.randomUUID(), role: "neuro", text: response.ok ? result.reply : result.error, matches: response.ok ? result.matches : [] }]); } catch { setMessages((current) => [...current, { id: crypto.randomUUID(), role: "neuro", text: "I couldn’t reach the live catalogue. Please try again in a moment." }]); } finally { setBusy(false); } }
  function submit(event: FormEvent) { event.preventDefault(); void ask(input); }
  return <div className="assistant-backdrop" onClick={(event) => { if (event.target === event.currentTarget) onClose(); }} role="presentation"><section className="assistant neuro-assistant" aria-label="Neuro shopping concierge"><header><div><img src="/branding/neurocity-mark.png" alt="" /><div><b>Neuro concierge</b><small><i /> Live catalogue intelligence</small></div></div><button onClick={onClose} aria-label="Close Neuro">×</button></header><div className="assistant-body neuro-thread" aria-live="polite">{messages.map((message) => <article className={`neuro-message ${message.role}`} key={message.id}><div>{message.role === "neuro" && <span>NC</span>}<p>{message.text}</p></div>{message.matches?.length ? <div className="neuro-results">{message.matches.map((match) => <article key={match.id}><img src={match.imageUrl ?? "/branding/neurocity-mark.png"} alt="" /><div><small>{match.store.name}{match.collection ? ` · ${match.collection}` : ""}</small><b>{match.name}</b><p>{match.colours.length ? match.colours.join(" · ") : "Published product"}{match.sizes.length ? ` · ${match.sizes.join("/")}` : ""}</p><strong>{money(match.price)}</strong>{match.availableUnits > 0 && <em>{match.availableUnits} available</em>}</div><a href={`/stores/${match.store.slug}#shop`}>View</a></article>)}</div> : null}</article>)}{busy && <div className="neuro-thinking"><span /><span /><span /><small>Searching live stores</small></div>}<div ref={endRef} /></div>{messages.length === 1 && <div className="suggestions neuro-prompts">{prompts.map((prompt) => <button key={prompt} onClick={() => void ask(prompt)}>{prompt}</button>)}</div>}<form onSubmit={submit}><label><span className="sr-only">Describe what you need</span><input value={input} maxLength={300} onChange={(event) => setInput(event.target.value)} placeholder="Try ‘black hoodie under N$1,000’" /></label><button disabled={busy || input.trim().length < 2}>{busy ? "…" : "Send"}</button></form><footer>Neuro only recommends products currently published by approved stores.</footer></section></div>;
}
