"use client";

import { type CSSProperties, useEffect, useState } from "react";
import { NeuroConcierge } from "./NeuroConcierge";

type Mall = { id: number; name: string; slug: string; city: string | null; country: string; tagline: string | null; logoUrl: string | null; markUrl: string | null; theme: { primary?: string; surface?: string }; storeCount: number; domain: string | null };

export default function NeuroCityNetworkHome({ directoryOnly = false }: { directoryOnly?: boolean }) {
  const [malls, setMalls] = useState<Mall[]>([]); const [loading, setLoading] = useState(true); const [jamesOpen, setJamesOpen] = useState(false); const [jamesPrompt, setJamesPrompt] = useState({ text: "", key: 0 });
  const askJames = (text = "") => { if (text) setJamesPrompt({ text, key: Date.now() }); setJamesOpen(true); };
  useEffect(() => { fetch("/api/malls").then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setMalls(data.malls ?? []); }).catch(() => setMalls([])).finally(() => setLoading(false)); }, []);
  return <main id="main-content" className="network-home">
    <header className="network-header"><a href="/" className="network-brand"><img src="/branding/neurocity-mark.png" alt="" /><span><b>Neuro</b><strong>City</strong><small>Namibia&apos;s connected shopping network</small></span></a><nav><a className={!directoryOnly ? "active" : ""} href="/">Home</a><a href="/marketplace">Marketplace</a><a className={directoryOnly ? "active" : ""} href="/malls">Digital malls</a><a href="/marketplace#stores">Stores</a></nav><div><button onClick={() => askJames()}>✦ Ask James</button><a href="/account">Account</a></div></header>
    {!directoryOnly && <><section className="network-hero"><div><p className="eyebrow"><span /> ONE NETWORK · MANY DESTINATIONS</p><h1>Namibia&apos;s shopping world, <em>connected.</em></h1><p>Discover independent local stores, shop the NeuroCity Marketplace, or enter the digital versions of Namibia&apos;s malls—all through one intelligent platform.</p><div><a className="primary" href="/marketplace">Shop the marketplace <span>→</span></a><a href="/malls">Explore digital malls</a></div><ul><li>One customer account</li><li>Live local catalogues</li><li>James across the network</li></ul></div><aside><div className="network-map"><i className="pulse p1" /><i className="pulse p2" /><i className="pulse p3" /><span className="network-node main"><img src="/branding/neurocity-mark.png" alt="" /><b>NeuroCity</b><small>Commerce network</small></span><span className="network-node market"><b>Marketplace</b><small>Namibian stores</small></span><span className="network-node malls"><b>Digital malls</b><small>{malls.length || "New"} destinations</small></span><span className="network-node james"><b>James</b><small>Live discovery</small></span></div></aside></section>
    <section className="network-paths"><article><span>01</span><div><small>SHOP ACROSS NAMIBIA</small><h2>NeuroCity Marketplace</h2><p>Browse products and independent merchants from one national marketplace.</p><a href="/marketplace">Enter marketplace →</a></div></article><article><span>02</span><div><small>ENTER A DESTINATION</small><h2>Digital malls</h2><p>Visit the online versions of participating shopping centres, each with its own identity and stores.</p><a href="/malls">Browse digital malls →</a></div></article><article><span>03</span><div><small>ASK NATURALLY</small><h2>James</h2><p>Search live catalogues across the network using a product, budget, colour, size or occasion.</p><button onClick={() => setJamesOpen(true)}>Start a conversation →</button></div></article></section></>}
    <section className={`network-malls ${directoryOnly ? "directory-page" : ""}`}><header><div><p className="eyebrow"><span /> DIGITAL DESTINATIONS</p><h2>{directoryOnly ? "Explore Namibia’s digital malls." : "The mall experience, extended online."}</h2></div><p>{directoryOnly ? "Enter a participating mall to browse its stores, products and services through a dedicated digital experience." : "Every mall keeps its own identity while connecting customers to the wider NeuroCity network."}</p></header>{loading ? <div className="mall-directory-empty">Loading digital malls…</div> : malls.length ? <div className="network-mall-grid">{malls.map((mall) => <article key={mall.id} style={{ "--mall-primary": mall.theme?.primary ?? "#18c98e", "--mall-surface": mall.theme?.surface ?? "#07111f" } as CSSProperties}><div className="mall-cover"><span>{mall.markUrl ? <img src={mall.markUrl} alt="" /> : mall.name.split(" ").map((word) => word[0]).join("").slice(0, 2)}</span><small>{mall.city ?? mall.country}</small></div><div><span>NEUROCITY DIGITAL MALL</span><h3>{mall.name}</h3><p>{mall.tagline ?? `Discover ${mall.name} online.`}</p><ul><li>{mall.storeCount} {mall.storeCount === 1 ? "store" : "stores"} live</li><li>{mall.domain ? "Custom domain connected" : "NeuroCity preview"}</li></ul><a href={`/malls/${mall.slug}`}>Enter digital mall <b>→</b></a></div></article>)}</div> : <div className="mall-directory-empty"><b>Digital malls are being prepared.</b><p>New destinations will appear here as partnerships launch.</p></div>}{!directoryOnly && <a className="all-malls-link" href="/malls">View all digital malls →</a>}</section>
    {!directoryOnly && <section className="network-james"><div><span>J</span><i className="james-online" /></div><article><p className="eyebrow">JAMES · LIVE SHOPPING COMPANION</p><h2>One question.<br />The whole network.</h2><p>Ask James to search the national marketplace, compare participating stores or focus on a specific digital mall.</p><button onClick={() => askJames()}>Ask James what you need →</button></article><aside>{["Find black running shoes under N$1,500 near me.", "Which digital mall has a birthday gift under N$800?", "Only show products currently in stock."].map((question) => <button key={question} onClick={() => askJames(question)}>“{question}” <span>Ask →</span></button>)}</aside></section>}
    <footer className="network-footer"><div className="network-brand"><img src="/branding/neurocity-mark.png" alt="" /><span><b>Neuro</b><strong>City</strong></span></div><p>Namibia&apos;s connected commerce and digital-mall network.</p><nav><a href="/marketplace">Marketplace</a><a href="/malls">Digital malls</a><a href="/apply">Become a merchant</a><a href="/admin">Administration</a></nav><small>© {new Date().getFullYear()} NeuroCity · Namibia</small></footer>
    <button className="network-james-fab" onClick={() => askJames()} aria-label="Open James">✦</button><NeuroConcierge open={jamesOpen} onClose={() => setJamesOpen(false)} initialPrompt={jamesPrompt.text} promptKey={jamesPrompt.key} />
  </main>;
}
