import { and, asc, eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { auditEvents, productVariants, products, storeBranches, variantInventory } from "../../../../db/schema";
import { requirePilotMerchant } from "../auth";

export async function GET() {
  const access = await requirePilotMerchant(); if (!access) return Response.json({ error: "Merchant authentication required." }, { status: 401 });
  const db = getDb(); const rows = await db.select({ id: productVariants.id, productId: productVariants.productId, productName: products.name, sku: productVariants.sku, title: productVariants.title, size: productVariants.size, color: productVariants.color, price: productVariants.price, salePrice: productVariants.salePrice, status: productVariants.status, imageUrl: productVariants.imageUrl }).from(productVariants).innerJoin(products, eq(products.id, productVariants.productId)).where(eq(products.merchantId, access.merchantId)).orderBy(asc(products.id), asc(productVariants.id));
  const stock = rows.length ? await db.select({ variantId: variantInventory.variantId, onHand: variantInventory.onHand, reserved: variantInventory.reserved, safetyStock: variantInventory.safetyStock, branchId: variantInventory.branchId, branchName: storeBranches.name }).from(variantInventory).innerJoin(storeBranches, eq(storeBranches.id, variantInventory.branchId)) : [];
  return Response.json({ variants: rows.map((row) => ({ ...row, stock: stock.filter((item) => item.variantId === row.id) })) });
}

export async function POST(request: Request) {
  const access = await requirePilotMerchant(["owner", "manager"]); if (!access) return Response.json({ error: "Owner or manager access required." }, { status: 403 });
  const payload = await request.json() as { productId?: number; sku?: string; title?: string; size?: string; color?: string; price?: number; salePrice?: number | null; onHand?: number };
  if (!Number.isInteger(payload.productId) || !payload.sku?.trim() || !payload.title?.trim() || !Number.isFinite(payload.price) || payload.price! < 0) return Response.json({ error: "Product, SKU, title and a valid price are required." }, { status: 400 });
  if (payload.salePrice != null && (!Number.isFinite(payload.salePrice) || payload.salePrice < 0 || payload.salePrice >= payload.price!)) return Response.json({ error: "Sale price must be lower than the regular price." }, { status: 400 });
  const db = getDb(); const [product] = await db.select().from(products).where(and(eq(products.id, payload.productId!), eq(products.merchantId, access.merchantId))).limit(1); if (!product) return Response.json({ error: "Product not found." }, { status: 404 });
  try { const [variant] = await db.insert(productVariants).values({ productId: product.id, sku: payload.sku.trim().toUpperCase(), title: payload.title.trim(), size: payload.size?.trim() || null, color: payload.color?.trim() || null, price: payload.price!, salePrice: payload.salePrice ?? null, status: "active", imageUrl: product.imageUrl }).returning(); const [branch] = await db.select().from(storeBranches).where(eq(storeBranches.merchantId, access.merchantId)).limit(1); if (branch) await db.insert(variantInventory).values({ variantId: variant.id, branchId: branch.id, onHand: Math.max(0, Math.floor(payload.onHand ?? 0)), reserved: 0, safetyStock: 0 }); await db.insert(auditEvents).values({ actorRef: access.user.userId, action: "product_variant.created", resourceType: "product_variant", resourceId: String(variant.id), metadata: { productId: product.id, sku: variant.sku } }); return Response.json({ variant }, { status: 201 }); } catch { return Response.json({ error: "SKU already exists or the variant could not be created." }, { status: 409 }); }
}

export async function PATCH(request: Request) {
  const access = await requirePilotMerchant(["owner", "manager"]); if (!access) return Response.json({ error: "Owner or manager access required." }, { status: 403 });
  const payload = await request.json() as { id?: number; title?: string; size?: string; color?: string; price?: number; salePrice?: number | null; status?: string; onHand?: number; safetyStock?: number };
  if (!Number.isInteger(payload.id) || !payload.title?.trim() || !Number.isFinite(payload.price) || payload.price! < 0 || !["active", "draft", "archived", "needs_confirmation"].includes(payload.status ?? "")) return Response.json({ error: "Valid variant details are required." }, { status: 400 });
  if (payload.salePrice != null && (!Number.isFinite(payload.salePrice) || payload.salePrice < 0 || payload.salePrice >= payload.price!)) return Response.json({ error: "Sale price must be lower than the regular price." }, { status: 400 });
  const db = getDb(); const [current] = await db.select({ id: productVariants.id }).from(productVariants).innerJoin(products, eq(products.id, productVariants.productId)).where(and(eq(productVariants.id, payload.id!), eq(products.merchantId, access.merchantId))).limit(1); if (!current) return Response.json({ error: "Variant not found." }, { status: 404 });
  const [variant] = await db.update(productVariants).set({ title: payload.title.trim(), size: payload.size?.trim() || null, color: payload.color?.trim() || null, price: payload.price!, salePrice: payload.salePrice ?? null, status: payload.status! }).where(eq(productVariants.id, current.id)).returning();
  const [branch] = await db.select().from(storeBranches).where(eq(storeBranches.merchantId, access.merchantId)).limit(1); if (branch && Number.isInteger(payload.onHand) && Number.isInteger(payload.safetyStock)) await db.insert(variantInventory).values({ variantId: variant.id, branchId: branch.id, onHand: Math.max(0, payload.onHand!), reserved: 0, safetyStock: Math.max(0, payload.safetyStock!) }).onConflictDoUpdate({ target: [variantInventory.variantId, variantInventory.branchId], set: { onHand: Math.max(0, payload.onHand!), safetyStock: Math.max(0, payload.safetyStock!), updatedAt: new Date() } });
  await db.insert(auditEvents).values({ actorRef: access.user.userId, action: "product_variant.updated", resourceType: "product_variant", resourceId: String(variant.id), metadata: { status: variant.status } }); return Response.json({ variant });
}
