/* eslint-disable react/no-unescaped-entities -- Legal prose contains possessives. */
import Link from "next/link";
import { PRIVACY_CONTACT_EMAIL, PRIVACY_NOTICE_VERSION } from "../../lib/privacy";

export const metadata = { title: "Privacy notice | NeuroCity", description: "How NeuroCity collects, uses and protects personal information." };

export default function PrivacyPage() {
  return <main className="legal-page">
    <nav><Link href="/" className="brand"><span>Neuro</span><strong>City</strong></Link><span><Link href="/terms">Terms</Link> · <Link href="/account">Privacy controls</Link></span></nav>
    <article>
      <p className="eyebrow">Privacy at NeuroCity</p>
      <h1>Your information should work for you—not travel farther than it needs to.</h1>
      <p className="legal-updated">Notice version {PRIVACY_NOTICE_VERSION} · Last updated 7 September 2026</p>
      <section><h2>Who is responsible</h2><p>NeuroCity operates this Namibian shopping, services and digital-mall platform. Questions and privacy requests can be sent to <a href={`mailto:${PRIVACY_CONTACT_EMAIL}`}>{PRIVACY_CONTACT_EMAIL}</a>.</p></section>
      <section><h2>Information we collect</h2><p>Depending on how you use NeuroCity, we process account and contact details; saved stores, wishlists and addresses; orders, bookings, messages and fulfilment details; payment status and customer-uploaded proof of payment; merchant application, representative, business and verification documents; and limited technical and security records.</p><p>NeuroCity does not store your raw password. Passwords are one-way hashed. Card or wallet credentials entered on a payment provider's hosted service are handled by that provider, not stored by NeuroCity.</p></section>
      <section><h2>Cookies and device storage</h2><p>NeuroCity uses essential cookies for signed-in sessions, Google sign-in state and security. Browser storage keeps requested features such as application drafts, guest chat and optional Selma memory on your device. Google Analytics loads only after you accept analytics in the privacy-choice banner. You can reject analytics and continue using the platform.</p></section>
      <section><h2>Why we use it and our legal bases</h2><ul><li><b>Contract:</b> to create accounts and operate carts, orders, bookings, payments and merchant services you request.</li><li><b>Legitimate interests:</b> to secure the platform, prevent fraud, improve reliability and answer support enquiries, after considering the effect on your rights.</li><li><b>Legal obligations:</b> to keep records required for accounting, tax, disputes, security incidents and lawful requests.</li><li><b>Consent:</b> for optional personalisation such as persistent Selma memory and any direct marketing. You can withdraw consent without affecting earlier lawful processing.</li></ul></section>
      <section><h2>Who receives it</h2><p>We disclose only what is needed to the relevant merchant for an order, booking or enquiry. We also use infrastructure, private file storage, email, security, artificial-intelligence and payment service providers to run NeuroCity. When you choose Selma&apos;s visual search, your selected image is sent to OpenAI to identify the item and produce catalogue search terms. NeuroCity does not save that image to your account or chat history. Avoid uploading images containing people, identity documents or other sensitive information. We do not sell personal information.</p></section>
      <section><h2>International transfers</h2><p>Some providers may process information outside Namibia or the country where you live. Where GDPR applies, NeuroCity must use a recognised transfer mechanism, such as an adequacy decision or approved contractual safeguards, and assess supplementary security measures where required. You may contact us for information about the safeguards relevant to your data.</p></section>
      <section><h2>Retention</h2><p>Account, cart and preference data is kept while the account is active and removed or de-identified after an approved deletion request, unless a longer period is required. Merchant verification records, orders, payment records, disputes, security logs and incident records are retained only for documented fraud-prevention, accounting, tax, contractual or legal periods. NeuroCity must maintain a written retention schedule with a named owner and review dates; where no legal or operational reason remains, information is deleted or de-identified.</p></section>
      <section><h2>Your choices and rights</h2><p>Where applicable, you may ask to access, correct, export, restrict or delete your personal information; object to processing based on legitimate interests; and withdraw optional consent. You may also complain to the data-protection authority where you live, work, or believe an infringement occurred. Some records cannot be deleted immediately where they are needed for a transaction, legal obligation, fraud prevention or dispute. Signed-in customers can download an account copy or submit a deletion request from Account → Privacy. Contact us for restriction, objection, correction or complaint-related requests.</p></section>
      <section><h2>Security</h2><p>NeuroCity uses encrypted HTTPS transport, private object storage with short-lived document links, hashed passwords and session tokens, role-based access, restricted file types and sizes, and browser security controls. No online system can promise absolute security; please use a unique password and report suspicious activity promptly.</p></section>
      <section><h2>Personal data breaches</h2><p>NeuroCity records and investigates personal-data incidents. Where GDPR applies, we notify the competent supervisory authority without undue delay and, where feasible, within 72 hours after becoming aware of a breach that is likely to create a risk to people. Where a breach is likely to create a high risk, we contact affected people without undue delay in clear language, describing what happened, likely consequences, measures taken and how to contact us.</p></section>
      <section><h2>Children and changes</h2><p>Customer accounts are intended for people able to enter a valid transaction, or those using the service with a parent or guardian. We will update this page and its version date when the notice materially changes.</p></section>
      <div className="legal-actions"><Link href="/account">Open account privacy controls</Link><a href={`mailto:${PRIVACY_CONTACT_EMAIL}`}>Contact privacy support</a></div>
    </article>
  </main>;
}
