"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type CustomerConversation = { id: number; storeName: string; storeSlug: string; productName: string | null; subject: string; status: string; lastMessageAt: string; messages: { id: number; senderRole: string; senderName: string; body: string; createdAt: string }[] };
type Account = { user: { displayName: string; email: string }; addresses: { id: number; label: string; recipientName: string; phone: string; addressLine1: string; suburb: string | null; city: string; isDefault: boolean }[]; wishlist: { id: number; productId: number; name: string; imageUrl: string | null; price: number | null; storeName: string; storeSlug: string }[]; savedStores: { id: number; merchantId: number; name: string; slug: string; logoUrl: string | null; tagline: string | null; status: string }[]; cart: { id: number; variantId: number; quantity: number; sku: string; size: string | null; color: string | null; price: number; salePrice: number | null; productName: string; imageUrl: string | null; storeName: string }[]; orders: { id: number; reference: string; status: string; total: number; fulfillmentMethod: string; createdAt: string; storeName: string; items: { id: number; nameSnapshot: string; quantity: number }[] }[]; conversations: CustomerConversation[] };
type Tab = "Overview" | "Messages" | "Orders" | "Bag" | "Wishlist" | "Stores" | "Addresses";
const blankAddress = { label: "Home", recipientName: "", phone: "", addressLine1: "", addressLine2: "", suburb: "", city: "Windhoek", deliveryNotes: "", isDefault: true };

export default function AccountPage() { const [data, setData] = useState<Account | null>(null); const [unauthorized, setUnauthorized] = useState(false); const [tab, setTab] = useState<Tab>("Overview"); const [address, setAddress] = useState(blankAddress); const [message, setMessage] = useState(""); const load = useCallback(async () => { const [response, conversationResponse] = await Promise.all([fetch("/api/account"), fetch("/api/conversations")]); if (response.status === 401) return setUnauthorized(true); const body = await response.json(); const conversationBody = conversationResponse.ok ? await conversationResponse.json() : { conversations: [] }; if (!response.ok) return setMessage(body.error); setData({ ...body, conversations: conversationBody.conversations }); }, []); useEffect(() => { load(); }, [load]); async function action(body: object) { const response = await fetch("/api/account", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); setMessage(response.ok ? "Account updated." : result.error); if (response.ok) await load(); } async function addAddress(event: FormEvent) { event.preventDefault(); await action({ action: "address", ...address }); setAddress(blankAddress); } async function removeAddress(id: number) { await fetch("/api/account", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ resource: "address", id }) }); await load(); } async function reply(conversationId: number, text: string) { const response = await fetch("/api/conversations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ conversationId, message: text }) }); const result = await response.json(); if (!response.ok) return setMessage(result.error); await load(); }
  if (unauthorized) return <main className="account-gate"><a href="/" className="brand"><span>Neuro</span><strong>City</strong></a><h1>Your NeuroCity account</h1><p>Sign in or create a customer account to save stores, products, addresses and orders.</p><a href="/login?return_to=%2Faccount">Continue to sign in</a></main>; if (!data) return <main className="account-gate"><p>Loading your account…</p></main>;
  const bagTotal = data.cart.reduce((sum, item) => sum + Number(item.salePrice ?? item.price) * item.quantity, 0);
  return <main className="customer-account"><aside><a href="/" className="brand"><span>Neuro</span><strong>City</strong></a><div><span>{data.user.displayName.slice(0, 1).toUpperCase()}</span><strong>{data.user.displayName}</strong><small>{data.user.email}</small></div><nav>{(["Overview", "Messages", "Orders", "Bag", "Wishlist", "Stores", "Addresses"] as Tab[]).map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}<b>{item === "Messages" ? data.conversations.filter((conversation) => conversation.status !== "closed").length : item === "Orders" ? data.orders.length : item === "Bag" ? data.cart.length : item === "Wishlist" ? data.wishlist.length : item === "Stores" ? data.savedStores.length : item === "Addresses" ? data.addresses.length : ""}</b></button>)}</nav><a href="/api/auth/logout?return_to=/">Sign out</a></aside><section><header><div><p className="eyebrow">Customer account</p><h1>{tab}</h1></div><a href="/">Continue shopping</a></header>{message && <button className="workspace-message" onClick={() => setMessage("")}>{message} ×</button>}
  {tab === "Overview" && <><div className="account-metrics"><article><span>Orders</span><strong>{data.orders.length}</strong></article><article><span>Bag items</span><strong>{data.cart.reduce((sum, item) => sum + item.quantity, 0)}</strong></article><article><span>Wishlist</span><strong>{data.wishlist.length}</strong></article><article><span>Saved stores</span><strong>{data.savedStores.length}</strong></article></div><div className="account-panel"><h2>Recent orders</h2>{data.orders.slice(0, 3).map((order) => <OrderRow key={order.id} order={order} />)}{data.orders.length === 0 && <p>No orders yet.</p>}</div></>}
  {tab === "Orders" && <div className="account-list">{data.orders.map((order) => <OrderRow key={order.id} order={order} />)}{data.orders.length === 0 && <Empty text="Your orders and tracking updates will appear here." />}</div>}
  {tab === "Messages" && <div className="inbox-list">{data.conversations.map((conversation) => <CustomerThread key={conversation.id} conversation={conversation} onReply={reply} />)}{data.conversations.length === 0 && <Empty text="Questions you send to stores will appear here." />}</div>}
  {tab === "Bag" && <div className="account-panel"><div className="account-panel-title"><h2>Shopping bag</h2><strong>N${bagTotal.toFixed(2)}</strong></div>{data.cart.map((item) => <article className="account-product-row" key={item.id}>{item.imageUrl && <img src={item.imageUrl} alt="" />}<div><strong>{item.productName}</strong><span>{[item.size, item.color].filter(Boolean).join(" / ")} · {item.sku}</span><small>{item.storeName}</small></div><input type="number" min="0" max="20" value={item.quantity} onChange={(event) => action({ action: "cart", variantId: item.variantId, quantity: Number(event.target.value) })} /><b>N${(Number(item.salePrice ?? item.price) * item.quantity).toFixed(2)}</b></article>)}{data.cart.length === 0 && <Empty text="Your saved bag will follow you across devices." />}</div>}
  {tab === "Wishlist" && <div className="account-grid">{data.wishlist.map((item) => <article key={item.id}>{item.imageUrl && <img src={item.imageUrl} alt="" />}<h3>{item.name}</h3><p>{item.storeName}</p><div><a href={`/stores/${item.storeSlug}`}>View product</a><button onClick={() => action({ action: "wishlist", productId: item.productId })}>Remove</button></div></article>)}{data.wishlist.length === 0 && <Empty text="Products you save will appear here." />}</div>}
  {tab === "Stores" && <div className="account-grid">{data.savedStores.map((store) => <article key={store.id}>{store.logoUrl && <img src={store.logoUrl} alt="" />}<h3>{store.name}</h3><p>{store.tagline}</p><div><a href={`/stores/${store.slug}`}>Visit store</a><button onClick={() => action({ action: "store", merchantId: store.merchantId })}>Remove</button></div></article>)}{data.savedStores.length === 0 && <Empty text="Save local stores for quick access." />}</div>}
  {tab === "Addresses" && <div className="address-layout"><div className="account-list">{data.addresses.map((item) => <article className="address-card" key={item.id}><div><strong>{item.label}{item.isDefault ? " · Default" : ""}</strong><span>{item.recipientName} · {item.phone}</span><p>{item.addressLine1}{item.suburb ? `, ${item.suburb}` : ""}, {item.city}</p></div><button onClick={() => removeAddress(item.id)}>Remove</button></article>)}</div><form onSubmit={addAddress}><h2>Add delivery address</h2><label>Label<input value={address.label} onChange={(event) => setAddress({ ...address, label: event.target.value })} /></label><label>Recipient<input required value={address.recipientName} onChange={(event) => setAddress({ ...address, recipientName: event.target.value })} /></label><label>Phone<input required value={address.phone} onChange={(event) => setAddress({ ...address, phone: event.target.value })} /></label><label>Street address<input required value={address.addressLine1} onChange={(event) => setAddress({ ...address, addressLine1: event.target.value })} /></label><label>Suburb<input value={address.suburb} onChange={(event) => setAddress({ ...address, suburb: event.target.value })} /></label><label>City<input value={address.city} onChange={(event) => setAddress({ ...address, city: event.target.value })} /></label><label className="address-default"><input type="checkbox" checked={address.isDefault} onChange={(event) => setAddress({ ...address, isDefault: event.target.checked })} /> Make default</label><button>Add address</button></form></div>}
  </section></main>; }

function OrderRow({ order }: { order: Account["orders"][number] }) { return <article className="account-order"><div><span>{order.reference}</span><strong>{order.storeName}</strong><small>{new Date(order.createdAt).toLocaleDateString("en-NA")}</small></div><div><span className="order-status">{order.status.replaceAll("_", " ")}</span><small>{order.fulfillmentMethod.replaceAll("_", " ")}</small></div><strong>N${Number(order.total).toFixed(2)}</strong></article>; }
function CustomerThread({ conversation, onReply }: { conversation: CustomerConversation; onReply: (id: number, text: string) => void }) { const [text, setText] = useState(""); return <article className="inbox-thread customer-thread"><header><div><span className={`review-status status-${conversation.status}`}>{conversation.status}</span><h3>{conversation.subject}</h3><p>{conversation.storeName}{conversation.productName ? ` · ${conversation.productName}` : ""}</p></div><a href={`/stores/${conversation.storeSlug}`}>Visit store</a></header><div className="thread-messages">{conversation.messages.map((message) => <div className={message.senderRole === "customer" ? "customer-message" : "merchant-message"} key={message.id}><strong>{message.senderName}</strong><p>{message.body}</p><small>{new Date(message.createdAt).toLocaleString("en-NA")}</small></div>)}</div>{conversation.status !== "closed" && <footer><textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Reply to the store…" /><button disabled={!text.trim()} onClick={() => { onReply(conversation.id, text); setText(""); }}>Send message</button></footer>}</article>; }
function Empty({ text }: { text: string }) { return <div className="account-empty"><strong>Nothing here yet</strong><p>{text}</p><a href="/">Explore NeuroCity</a></div>; }
