import { and, desc, eq, inArray } from "drizzle-orm";
import { getDb } from "../../../db";
import { customerAddresses, customerCartItems, customerSavedStores, customerWishlists, merchants, orderIssues, orderItems, orders, orderStatusEvents, paymentProofs, productVariants, products, serviceBookings } from "../../../db/schema";
import { getChatGPTUser } from "../../chatgpt-auth";

export async function GET() {
  const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in required." }, { status: 401 }); const userId = Number(user.userId); const db = getDb();
  const addresses = await db.select().from(customerAddresses).where(eq(customerAddresses.userId, userId)).orderBy(desc(customerAddresses.isDefault), desc(customerAddresses.createdAt));
  const wishlist = await db.select({ id: customerWishlists.id, productId: products.id, name: products.name, imageUrl: products.imageUrl, price: products.price, storeName: merchants.name, storeSlug: merchants.slug }).from(customerWishlists).innerJoin(products, eq(products.id, customerWishlists.productId)).innerJoin(merchants, eq(merchants.id, products.merchantId)).where(eq(customerWishlists.userId, userId));
  const savedStores = await db.select({ id: customerSavedStores.id, merchantId: merchants.id, name: merchants.name, slug: merchants.slug, logoUrl: merchants.logoUrl, tagline: merchants.tagline, status: merchants.status }).from(customerSavedStores).innerJoin(merchants, eq(merchants.id, customerSavedStores.merchantId)).where(eq(customerSavedStores.userId, userId));
  const cartRows = await db.select({ id: customerCartItems.id, variantId: productVariants.id, quantity: customerCartItems.quantity, sku: productVariants.sku, title: productVariants.title, size: productVariants.size, color: productVariants.color, price: productVariants.price, salePrice: productVariants.salePrice, productName: products.name, imageUrl: products.imageUrl, merchantId: merchants.id, storeName: merchants.name, storeSlug: merchants.slug, fulfillmentMethods: merchants.fulfillmentMethods, paymentSettings: merchants.paymentSettings }).from(customerCartItems).innerJoin(productVariants, eq(productVariants.id, customerCartItems.variantId)).innerJoin(products, eq(products.id, productVariants.productId)).innerJoin(merchants, eq(merchants.id, products.merchantId)).where(eq(customerCartItems.userId, userId));
  const cart = cartRows.map(({ paymentSettings: _paymentSettings, ...item }) => ({ ...item, paymentMethods: ["paytoday"] }));
  const customerOrders = await db.select({ id: orders.id, status: orders.status, paymentStatus: orders.paymentStatus, total: orders.total, subtotal: orders.subtotal, deliveryFee: orders.deliveryFee, fulfillmentMethod: orders.fulfillmentMethod, paymentMethod: orders.paymentMethod, paymentInstructions: orders.paymentInstructions, createdAt: orders.createdAt, storeName: merchants.name, storeSlug: merchants.slug }).from(orders).innerJoin(merchants, eq(merchants.id, orders.merchantId)).where(eq(orders.customerRef, user.userId)).orderBy(desc(orders.createdAt));
  const items = customerOrders.length ? await db.select().from(orderItems).where(inArray(orderItems.orderId, customerOrders.map((order) => order.id))) : [];
  const events = customerOrders.length ? await db.select().from(orderStatusEvents).where(inArray(orderStatusEvents.orderId, customerOrders.map((order) => order.id))).orderBy(desc(orderStatusEvents.createdAt)) : [];
  const proofs = customerOrders.length ? await db.select({ id: paymentProofs.id, orderId: paymentProofs.orderId, status: paymentProofs.status, originalName: paymentProofs.originalName, reviewNote: paymentProofs.reviewNote }).from(paymentProofs).where(inArray(paymentProofs.orderId, customerOrders.map((order) => order.id))) : [];
  const issues = customerOrders.length ? await db.select().from(orderIssues).where(inArray(orderIssues.orderId, customerOrders.map((order) => order.id))).orderBy(desc(orderIssues.createdAt)) : [];
  const bookings = await db.select({ id: serviceBookings.id, status: serviceBookings.status, requestedStart: serviceBookings.requestedStart, scheduledStart: serviceBookings.scheduledStart, durationMinutes: serviceBookings.durationMinutes, serviceMode: serviceBookings.serviceMode, priceSnapshot: serviceBookings.priceSnapshot, pricingModel: serviceBookings.pricingModel, customerNotes: serviceBookings.customerNotes, merchantNote: serviceBookings.merchantNote, createdAt: serviceBookings.createdAt, serviceName: products.name, storeName: merchants.name, storeSlug: merchants.slug }).from(serviceBookings).innerJoin(products, eq(products.id, serviceBookings.productId)).innerJoin(merchants, eq(merchants.id, serviceBookings.merchantId)).where(eq(serviceBookings.customerId, userId)).orderBy(desc(serviceBookings.createdAt));
  return Response.json({ user, addresses, wishlist, savedStores, cart, bookings: bookings.map((booking) => ({ ...booking, reference: `NCB-${String(booking.id).padStart(6, "0")}` })), orders: customerOrders.map((order) => ({ ...order, reference: `NC-${String(order.id).padStart(6, "0")}`, items: items.filter((item) => item.orderId === order.id), events: events.filter((event) => event.orderId === order.id), paymentProof: proofs.find((proof) => proof.orderId === order.id) ?? null, issues: issues.filter((issue) => issue.orderId === order.id) })) });
}

export async function POST(request: Request) {
  const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in required." }, { status: 401 }); const userId = Number(user.userId); const payload = await request.json() as Record<string, unknown>; const action = String(payload.action ?? ""); const db = getDb();
  if (action === "address") { const label = String(payload.label ?? "").trim(), recipientName = String(payload.recipientName ?? "").trim(), phone = String(payload.phone ?? "").trim(), addressLine1 = String(payload.addressLine1 ?? "").trim(); if (!label || !recipientName || !phone || !addressLine1) return Response.json({ error: "Label, recipient, phone and address are required." }, { status: 400 }); const makeDefault = payload.isDefault === true; const [address] = await db.transaction(async (tx) => { if (makeDefault) await tx.update(customerAddresses).set({ isDefault: false }).where(eq(customerAddresses.userId, userId)); return tx.insert(customerAddresses).values({ userId, label, recipientName, phone, addressLine1, addressLine2: String(payload.addressLine2 ?? "").trim() || null, suburb: String(payload.suburb ?? "").trim() || null, city: String(payload.city ?? "Windhoek").trim() || "Windhoek", deliveryNotes: String(payload.deliveryNotes ?? "").trim() || null, isDefault: makeDefault }).returning(); }); return Response.json({ address }, { status: 201 }); }
  if (action === "wishlist") { const productId = Number(payload.productId); if (!Number.isInteger(productId)) return Response.json({ error: "Valid product required." }, { status: 400 }); const [existing] = await db.select().from(customerWishlists).where(and(eq(customerWishlists.userId, userId), eq(customerWishlists.productId, productId))).limit(1); if (existing) await db.delete(customerWishlists).where(eq(customerWishlists.id, existing.id)); else await db.insert(customerWishlists).values({ userId, productId }); return Response.json({ saved: !existing }); }
  if (action === "store") { const merchantId = Number(payload.merchantId); if (!Number.isInteger(merchantId)) return Response.json({ error: "Valid store required." }, { status: 400 }); const [existing] = await db.select().from(customerSavedStores).where(and(eq(customerSavedStores.userId, userId), eq(customerSavedStores.merchantId, merchantId))).limit(1); if (existing) await db.delete(customerSavedStores).where(eq(customerSavedStores.id, existing.id)); else await db.insert(customerSavedStores).values({ userId, merchantId }); return Response.json({ saved: !existing }); }
  if (action === "cart") { const variantId = Number(payload.variantId), quantity = Number(payload.quantity); if (!Number.isInteger(variantId) || !Number.isInteger(quantity) || quantity < 0 || quantity > 20) return Response.json({ error: "Valid variant and quantity required." }, { status: 400 }); if (quantity === 0) await db.delete(customerCartItems).where(and(eq(customerCartItems.userId, userId), eq(customerCartItems.variantId, variantId))); else await db.insert(customerCartItems).values({ userId, variantId, quantity }).onConflictDoUpdate({ target: [customerCartItems.userId, customerCartItems.variantId], set: { quantity, updatedAt: new Date() } }); return Response.json({ ok: true }); }
  return Response.json({ error: "Unsupported account action." }, { status: 400 });
}

export async function DELETE(request: Request) { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in required." }, { status: 401 }); const { id, resource } = await request.json() as { id?: number; resource?: string }; if (!Number.isInteger(id)) return Response.json({ error: "Valid record required." }, { status: 400 }); if (resource === "address") await getDb().delete(customerAddresses).where(and(eq(customerAddresses.id, id!), eq(customerAddresses.userId, Number(user.userId)))); else return Response.json({ error: "Unsupported account resource." }, { status: 400 }); return Response.json({ ok: true }); }
