import { and, desc, eq, inArray } from "drizzle-orm";
import { getDb } from "../../../../db";
import { conversationMessages, merchantMemberships, products, storeConversations, users } from "../../../../db/schema";
import { requirePilotMerchant } from "../auth";

export async function GET() { const access = await requirePilotMerchant(); if (!access) return Response.json({ error: "Merchant access required." }, { status: 403 }); const db = getDb(); const conversations = await db.select({ id: storeConversations.id, customerId: storeConversations.customerId, customerName: users.displayName, customerEmail: users.email, productId: storeConversations.productId, productName: products.name, subject: storeConversations.subject, status: storeConversations.status, assignedMembershipId: storeConversations.assignedMembershipId, source: storeConversations.source, lastMessageAt: storeConversations.lastMessageAt }).from(storeConversations).innerJoin(users, eq(users.id, storeConversations.customerId)).leftJoin(products, eq(products.id, storeConversations.productId)).where(eq(storeConversations.merchantId, access.merchantId)).orderBy(desc(storeConversations.lastMessageAt)); const messages = conversations.length ? await db.select({ id: conversationMessages.id, conversationId: conversationMessages.conversationId, senderRole: conversationMessages.senderRole, senderName: users.displayName, body: conversationMessages.body, createdAt: conversationMessages.createdAt }).from(conversationMessages).innerJoin(users, eq(users.id, conversationMessages.senderUserId)).where(inArray(conversationMessages.conversationId, conversations.map((item) => item.id))) : []; return Response.json({ conversations: conversations.map((item) => ({ ...item, messages: messages.filter((message) => message.conversationId === item.id) })) }); }

export async function POST(request: Request) { const access = await requirePilotMerchant(); if (!access) return Response.json({ error: "Merchant access required." }, { status: 403 }); const { conversationId, message } = await request.json() as { conversationId?: number; message?: string }; if (!Number.isInteger(conversationId) || !message?.trim() || message.trim().length > 4000) return Response.json({ error: "Valid conversation and message required." }, { status: 400 }); const db = getDb(); const [conversation] = await db.select().from(storeConversations).where(and(eq(storeConversations.id, conversationId!), eq(storeConversations.merchantId, access.merchantId))).limit(1); if (!conversation || conversation.status === "closed") return Response.json({ error: "Conversation unavailable or closed." }, { status: 404 }); const [created] = await db.insert(conversationMessages).values({ conversationId: conversation.id, senderUserId: Number(access.user.userId), senderRole: "merchant", body: message.trim() }).returning(); await db.update(storeConversations).set({ lastMessageAt: new Date(), status: "open", assignedMembershipId: access.membership.id }).where(eq(storeConversations.id, conversation.id)); return Response.json({ message: created }, { status: 201 }); }

export async function PATCH(request: Request) { const access = await requirePilotMerchant(); if (!access) return Response.json({ error: "Merchant access required." }, { status: 403 }); const { conversationId, status, assignToMe } = await request.json() as { conversationId?: number; status?: string; assignToMe?: boolean }; if (!Number.isInteger(conversationId) || (status && !["open", "pending", "closed"].includes(status))) return Response.json({ error: "Valid conversation update required." }, { status: 400 }); const values: { status?: string; assignedMembershipId?: number } = {}; if (status) values.status = status; if (assignToMe) values.assignedMembershipId = access.membership.id; const [updated] = await getDb().update(storeConversations).set(values).where(and(eq(storeConversations.id, conversationId!), eq(storeConversations.merchantId, access.merchantId))).returning(); if (!updated) return Response.json({ error: "Conversation not found." }, { status: 404 }); return Response.json({ conversation: updated }); }
