import Link from "next/link";
import { PRIVACY_CONTACT_EMAIL, TERMS_VERSION } from "../../lib/privacy";

export const metadata = { title: "Terms & Conditions | NeuroCity", description: "The terms for using NeuroCity as a customer or merchant." };

export default function TermsPage() {
  return <main className="legal-page">
    <nav><Link href="/" className="brand"><span>Neuro</span><strong>City</strong></Link><Link href="/privacy">Privacy notice</Link></nav>
    <article>
      <p className="eyebrow">NeuroCity platform terms</p>
      <h1>Terms &amp; Conditions</h1>
      <p className="legal-updated">Version {TERMS_VERSION} · Effective 31 August 2026</p>
      <section><h2>1. Agreement and eligibility</h2><p>By creating an account, submitting a merchant application, or placing an order or booking, you agree to these terms and the NeuroCity privacy notice. You must provide accurate information, keep your credentials secure, and be legally able to enter the relevant transaction. If you act for a business, you confirm that you are authorised to bind it.</p></section>
      <section><h2>2. NeuroCity’s role</h2><p>NeuroCity provides a digital marketplace and digital-mall platform connecting customers with independent merchants and service providers. Unless expressly stated otherwise, the merchant—not NeuroCity—is the seller or service provider and is responsible for descriptions, availability, quality, safety, lawful supply, warranties, returns and fulfilment.</p></section>
      <section><h2>3. Accounts and acceptable use</h2><p>You may not misuse the platform, impersonate another person, upload unlawful or malicious material, interfere with security, scrape protected information, manipulate orders or payments, or use NeuroCity to sell prohibited or unlawful goods or services. We may restrict access to protect customers, merchants or the platform.</p></section>
      <section><h2>4. Orders, bookings and availability</h2><p>An order or booking request is subject to merchant confirmation, stock or schedule availability and payment requirements. Prices, delivery fees and the final total are displayed before confirmation. Merchants must promptly correct catalogue errors and communicate substitutions, delays or cancellations.</p></section>
      <section><h2>5. Payments and merchant settlement</h2><p>Where NeuroCity checkout is used, the customer pays one combined invoice to NeuroCity’s designated PayToday channel. NeuroCity records the amount allocated to each participating merchant. Eligible merchant amounts are scheduled for settlement two business days after confirmed payment (T+2), subject to authorised fees, refunds, reversals, fraud checks or disputes. Weekends and banking interruptions may affect the processing date. Payment-provider terms may also apply.</p></section>
      <section><h2>6. Delivery, collection and services</h2><p>The checkout identifies the agreed fulfilment method. Delivery estimates are estimates unless expressly guaranteed. Customers must provide a usable address and contact details. Service outcomes, appointment requirements and cancellation conditions are set by the relevant provider and must be shown before confirmation where applicable.</p></section>
      <section><h2>7. Returns, refunds and disputes</h2><p>The relevant merchant’s disclosed return or cancellation policy applies, subject to applicable Namibian consumer law. Customers should raise an issue through the order or booking record. Refunds may require merchant review and payment-provider processing time. Nothing in these terms excludes rights that cannot lawfully be excluded.</p></section>
      <section><h2>8. Merchant obligations</h2><p>Merchants must keep registration, contact, banking, location and authorised-representative information current; maintain accurate prices, variants, inventory and service availability; fulfil accepted transactions; protect customer information; comply with applicable laws; and notify NeuroCity of security, ownership or banking changes. Approval, publication, suspension or removal may depend on verification and ongoing compliance.</p></section>
      <section><h2>9. Content and intellectual property</h2><p>You retain ownership of content you upload and grant NeuroCity a non-exclusive licence to host, resize and display it for operating and promoting the platform and relevant storefront. You must have the rights to use all names, logos, images and descriptions submitted. NeuroCity branding, software and platform materials remain protected.</p></section>
      <section><h2>10. Selma and automated assistance</h2><p>Selma helps customers discover catalogue information but may misunderstand a request or reflect outdated merchant information. Confirm price, variant, availability and important terms before purchasing. Automated assistance is not professional, financial or legal advice.</p></section>
      <section><h2>11. Availability and responsibility</h2><p>We work to keep NeuroCity secure and available but cannot guarantee uninterrupted operation. To the extent permitted by law, NeuroCity is not responsible for indirect losses or an independent merchant’s acts, products or services. This does not limit responsibility that cannot lawfully be limited.</p></section>
      <section><h2>12. Suspension, termination and changes</h2><p>You may stop using NeuroCity and request account deletion through the privacy controls. We may suspend or terminate accounts for material breach, fraud, security risk or legal necessity. Transaction and compliance records may be retained where required. Material term changes will be dated and, where appropriate, presented for renewed acceptance.</p></section>
      <section><h2>13. Governing framework and contact</h2><p>These terms are governed by the laws applicable in Namibia. Before court proceedings, the parties should first attempt to resolve a dispute through NeuroCity support, without limiting any lawful right to approach a regulator or court. Contact <a href={`mailto:${PRIVACY_CONTACT_EMAIL}`}>{PRIVACY_CONTACT_EMAIL}</a>.</p></section>
      <div className="legal-actions"><Link href="/login?mode=register">Create an account</Link><Link href="/privacy">Read the privacy notice</Link></div>
    </article>
  </main>;
}
