import { and, desc, eq, inArray } from "drizzle-orm";
import { getDb } from "../../../db";
import { conversationMessages, merchants, products, storeConversations, users } from "../../../db/schema";
import { getChatGPTUser } from "../../chatgpt-auth";

export async function GET() { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in required." }, { status: 401 }); const db = getDb(); const conversations = await db.select({ id: storeConversations.id, merchantId: storeConversations.merchantId, storeName: merchants.name, storeSlug: merchants.slug, productId: storeConversations.productId, productName: products.name, subject: storeConversations.subject, status: storeConversations.status, lastMessageAt: storeConversations.lastMessageAt, createdAt: storeConversations.createdAt }).from(storeConversations).innerJoin(merchants, eq(merchants.id, storeConversations.merchantId)).leftJoin(products, eq(products.id, storeConversations.productId)).where(eq(storeConversations.customerId, Number(user.userId))).orderBy(desc(storeConversations.lastMessageAt)); const messages = conversations.length ? await db.select({ id: conversationMessages.id, conversationId: conversationMessages.conversationId, senderRole: conversationMessages.senderRole, senderName: users.displayName, body: conversationMessages.body, createdAt: conversationMessages.createdAt }).from(conversationMessages).innerJoin(users, eq(users.id, conversationMessages.senderUserId)).where(inArray(conversationMessages.conversationId, conversations.map((item) => item.id))) : []; return Response.json({ conversations: conversations.map((item) => ({ ...item, messages: messages.filter((message) => message.conversationId === item.id) })) }); }

export async function POST(request: Request) { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in required." }, { status: 401 }); const payload = await request.json() as { merchantId?: number; productId?: number; conversationId?: number; subject?: string; message?: string }; const message = payload.message?.trim(); if (!message || message.length > 4000) return Response.json({ error: "A message of up to 4,000 characters is required." }, { status: 400 }); const db = getDb(); let conversationId = payload.conversationId;
  if (conversationId) { const [conversation] = await db.select().from(storeConversations).where(and(eq(storeConversations.id, conversationId), eq(storeConversations.customerId, Number(user.userId)))).limit(1); if (!conversation || conversation.status === "closed") return Response.json({ error: "Conversation is unavailable or closed." }, { status: 404 }); }
  else { if (!Number.isInteger(payload.merchantId)) return Response.json({ error: "Valid store required." }, { status: 400 }); const [store] = await db.select().from(merchants).where(eq(merchants.id, payload.merchantId!)).limit(1); if (!store || !store.isPublic || !["pilot", "onboarding", "active"].includes(store.status)) return Response.json({ error: "Store unavailable." }, { status: 404 }); if (payload.productId) { const [product] = await db.select().from(products).where(and(eq(products.id, payload.productId), eq(products.merchantId, store.id))).limit(1); if (!product) return Response.json({ error: "Product not found." }, { status: 404 }); } const [created] = await db.insert(storeConversations).values({ merchantId: store.id, customerId: Number(user.userId), productId: payload.productId ?? null, subject: payload.subject?.trim().slice(0, 240) || "Store enquiry", status: "open", source: "neurocity" }).returning(); conversationId = created.id; }
  const [createdMessage] = await db.insert(conversationMessages).values({ conversationId: conversationId!, senderUserId: Number(user.userId), senderRole: "customer", body: message }).returning(); await db.update(storeConversations).set({ lastMessageAt: new Date(), status: "open" }).where(eq(storeConversations.id, conversationId!)); return Response.json({ conversationId, message: createdMessage }, { status: 201 }); }

export async function PATCH(request: Request) { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in required." }, { status: 401 }); const { conversationId, status } = await request.json() as { conversationId?: number; status?: string }; if (!Number.isInteger(conversationId) || !["open", "closed"].includes(status ?? "")) return Response.json({ error: "Valid conversation update required." }, { status: 400 }); const [updated] = await getDb().update(storeConversations).set({ status }).where(and(eq(storeConversations.id, conversationId!), eq(storeConversations.customerId, Number(user.userId)))).returning(); if (!updated) return Response.json({ error: "Conversation not found." }, { status: 404 }); return Response.json({ conversation: updated }); }
