import { randomUUID } from "node:crypto";
import { and, eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { auditEvents, merchantMemberships, orders, paymentProofs } from "../../../../db/schema";
import { allowedDocumentMimeTypes, createPresignedR2Url, maxDocumentBytes } from "../../../../lib/r2";
import { getChatGPTUser } from "../../../chatgpt-auth";

async function accessibleOrder(orderId: number, user: NonNullable<Awaited<ReturnType<typeof getChatGPTUser>>>) { const db = getDb(); const [order] = await db.select().from(orders).where(eq(orders.id, orderId)).limit(1); if (!order) return null; if (order.customerRef === user.userId || user.platformRole === "administrator") return order; const [membership] = await db.select().from(merchantMemberships).where(and(eq(merchantMemberships.merchantId, order.merchantId), eq(merchantMemberships.userRef, user.userId), eq(merchantMemberships.status, "active"))).limit(1); return membership ? order : null; }

export async function GET(request: Request) { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in required." }, { status: 401 }); const url = new URL(request.url); const orderId = Number(url.searchParams.get("orderId")); if (!Number.isInteger(orderId)) return Response.json({ error: "Valid order required." }, { status: 400 }); const order = await accessibleOrder(orderId, user); if (!order) return Response.json({ error: "Order not found." }, { status: 404 }); const [proof] = await getDb().select().from(paymentProofs).where(eq(paymentProofs.orderId, order.id)).limit(1); if (!proof || !["uploaded", "verified", "rejected"].includes(proof.status)) return Response.json({ error: "Payment proof unavailable." }, { status: 404 }); const disposition = url.searchParams.get("view") === "1" ? "inline" : "attachment"; return Response.redirect(createPresignedR2Url("GET", proof.storageKey, 120, `${disposition}; filename="${proof.originalName.replace(/["\r\n]/g, "-")}"`)); }

export async function POST(request: Request) { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in required." }, { status: 401 }); const payload = await request.json() as { orderId?: number; filename?: string; mimeType?: string; sizeBytes?: number }; if (!Number.isInteger(payload.orderId) || !payload.filename || !payload.mimeType || !allowedDocumentMimeTypes.has(payload.mimeType) || !Number.isInteger(payload.sizeBytes) || payload.sizeBytes! < 1 || payload.sizeBytes! > maxDocumentBytes) return Response.json({ error: "Upload a PDF, JPG or PNG no larger than 10 MB." }, { status: 400 }); const db = getDb(); const [order] = await db.select().from(orders).where(and(eq(orders.id, payload.orderId!), eq(orders.customerRef, user.userId), eq(orders.paymentMethod, "eft"))).limit(1); if (!order || ["paid", "refunded"].includes(order.paymentStatus)) return Response.json({ error: "This order is not eligible for a payment-proof upload." }, { status: 409 }); const safeName = payload.filename.replace(/[^a-zA-Z0-9._-]+/g, "-").slice(-120); const key = `payments/${order.id}/${randomUUID()}-${safeName}`; await db.insert(paymentProofs).values({ orderId: order.id, storageKey: key, originalName: payload.filename, mimeType: payload.mimeType, sizeBytes: payload.sizeBytes!, status: "upload_pending" }).onConflictDoUpdate({ target: paymentProofs.orderId, set: { storageKey: key, originalName: payload.filename, mimeType: payload.mimeType, sizeBytes: payload.sizeBytes!, status: "upload_pending", reviewNote: null, reviewedBy: null, reviewedAt: null, createdAt: new Date() } }); return Response.json({ uploadUrl: createPresignedR2Url("PUT", key, 600) }); }

export async function PATCH(request: Request) { const user = await getChatGPTUser(); if (!user) return Response.json({ error: "Sign in required." }, { status: 401 }); const { orderId } = await request.json() as { orderId?: number }; if (!Number.isInteger(orderId)) return Response.json({ error: "Valid order required." }, { status: 400 }); const db = getDb(); const [proof] = await db.select({ id: paymentProofs.id, storageKey: paymentProofs.storageKey }).from(paymentProofs).innerJoin(orders, eq(orders.id, paymentProofs.orderId)).where(and(eq(paymentProofs.orderId, orderId!), eq(orders.customerRef, user.userId))).limit(1); if (!proof) return Response.json({ error: "Upload record not found." }, { status: 404 }); const object = await fetch(createPresignedR2Url("HEAD", proof.storageKey, 60), { method: "HEAD" }); const size = Number(object.headers.get("content-length")); if (!object.ok || !Number.isInteger(size) || size < 1 || size > maxDocumentBytes) return Response.json({ error: "Uploaded file failed validation." }, { status: 409 }); await db.transaction(async (tx) => { await tx.update(paymentProofs).set({ status: "uploaded", sizeBytes: size }).where(eq(paymentProofs.id, proof.id)); await tx.update(orders).set({ paymentStatus: "proof_submitted", updatedAt: new Date() }).where(eq(orders.id, orderId!)); await tx.insert(auditEvents).values({ actorRef: user.userId, action: "payment_proof.submitted", resourceType: "order", resourceId: String(orderId) }); }); return Response.json({ ok: true }); }
