import { and, asc, eq, inArray, ne } from "drizzle-orm";
import { getDb } from "../../../../db";
import { auditEvents, checkoutGroups, merchantPaymentAllocations, merchants, orders, products, serviceBookings, users } from "../../../../db/schema";
import { sendBookingStatusNotification } from "../../../../lib/booking-mail";
import { openServicePayment } from "../../../../lib/service-payments";
import { requirePilotMerchant } from "../auth";

const transitions: Record<string, string[]> = { requested: ["confirmed", "declined", "reschedule_proposed"], quote_proposed: ["declined"], reschedule_proposed: ["declined"], confirmed: ["in_progress", "cancelled", "reschedule_proposed"], in_progress: ["completed", "cancelled"], completed: [], declined: [], cancelled: [] };
export async function GET() {
  const access = await requirePilotMerchant(); if (!access) return Response.json({ error: "Merchant authentication required." }, { status: 401 });
  const rows = await getDb().select({ id: serviceBookings.id, status: serviceBookings.status, requestedStart: serviceBookings.requestedStart, scheduledStart: serviceBookings.scheduledStart, durationMinutes: serviceBookings.durationMinutes, serviceMode: serviceBookings.serviceMode, priceSnapshot: serviceBookings.priceSnapshot, pricingModel: serviceBookings.pricingModel, customerNotes: serviceBookings.customerNotes, merchantNote: serviceBookings.merchantNote, orderId: serviceBookings.orderId, paymentStatus: serviceBookings.paymentStatus, paymentExpiresAt: serviceBookings.paymentExpiresAt, createdAt: serviceBookings.createdAt, serviceName: products.name, customerName: users.displayName, customerEmail: users.email }).from(serviceBookings).innerJoin(products, eq(products.id, serviceBookings.productId)).innerJoin(users, eq(users.id, serviceBookings.customerId)).where(eq(serviceBookings.merchantId, access.merchantId)).orderBy(asc(serviceBookings.requestedStart));
  return Response.json({ bookings: rows.map((row) => ({ ...row, reference: `NCB-${String(row.id).padStart(6, "0")}`, allowedTransitions: transitions[row.status] ?? [] })) }, { headers: { "cache-control": "no-store" } });
}
export async function PATCH(request: Request) {
  const access = await requirePilotMerchant(["owner", "manager"]); if (!access) return Response.json({ error: "Owner or manager access required." }, { status: 403 });
  const payload = await request.json() as { id?: number; status?: string; scheduledStart?: string; note?: string; quotePrice?: number };
  if (!Number.isInteger(payload.id) || !payload.status) return Response.json({ error: "Valid booking and status required." }, { status: 400 });
  const db = getDb(); const [current] = await db.select().from(serviceBookings).where(and(eq(serviceBookings.id, payload.id!), eq(serviceBookings.merchantId, access.merchantId))).limit(1);
  if (!current) return Response.json({ error: "Booking not found." }, { status: 404 });
  if (!(transitions[current.status] ?? []).includes(payload.status)) return Response.json({ error: `Cannot move this booking from ${current.status} to ${payload.status}.` }, { status: 409 });
  if (payload.status === "in_progress" && current.paymentStatus !== "paid") return Response.json({ error: "Wait for PayToday to verify payment before starting the service." }, { status: 409 });
  if (payload.status === "reschedule_proposed" && current.orderId && current.paymentStatus !== "paid") return Response.json({ error: "The customer payment window is already open. Cancel the unpaid booking or wait for payment before rescheduling." }, { status: 409 });
  const quoted = ["quote", "from"].includes(current.pricingModel);
  const quotePrice = Number(payload.quotePrice);
  if (payload.status === "confirmed" && quoted && (!Number.isFinite(quotePrice) || quotePrice <= 0)) return Response.json({ error: "Enter the final service price for the customer." }, { status: 400 });
  if (payload.status === "confirmed" && !quoted && (!Number.isFinite(Number(current.priceSnapshot)) || Number(current.priceSnapshot) <= 0)) return Response.json({ error: "Set a valid service price on the listing before confirming this booking." }, { status: 409 });
  const targetStatus = payload.status === "confirmed" && quoted ? "quote_proposed" : payload.status;
  const scheduledStart = payload.scheduledStart ? new Date(payload.scheduledStart) : payload.status === "confirmed" ? current.requestedStart : current.scheduledStart;
  if (["confirmed", "reschedule_proposed"].includes(payload.status) && (!scheduledStart || Number.isNaN(scheduledStart.getTime()) || scheduledStart.getTime() < Date.now())) return Response.json({ error: "Choose a future appointment time." }, { status: 400 });
  if (payload.status === "confirmed" && scheduledStart) { const [conflict] = await db.select({ id: serviceBookings.id }).from(serviceBookings).where(and(eq(serviceBookings.merchantId, access.merchantId), eq(serviceBookings.scheduledStart, scheduledStart), inArray(serviceBookings.status, ["confirmed", "in_progress"]), ne(serviceBookings.id, current.id))).limit(1); if (conflict) return Response.json({ error: "That appointment time has already been confirmed for another customer." }, { status: 409 }); }
  const updated = await db.transaction(async (tx) => { const at = new Date(); const [row] = await tx.update(serviceBookings).set({ status: targetStatus!, scheduledStart, priceSnapshot: quoted && payload.status === "confirmed" ? quotePrice : current.priceSnapshot, merchantNote: payload.note?.trim().slice(0, 1000) || null, updatedAt: at }).where(and(eq(serviceBookings.id, current.id), eq(serviceBookings.status, current.status))).returning(); if (!row) return null; if (targetStatus === "confirmed" && row.paymentStatus !== "paid") { const [product] = await tx.select({ id: products.id, sku: products.sku, name: products.name }).from(products).where(eq(products.id, row.productId)).limit(1); const [customer] = await tx.select({ displayName: users.displayName, email: users.email }).from(users).where(eq(users.id, row.customerId)).limit(1); if (!product || !customer) throw new Error("Booking payment details could not be prepared."); await openServicePayment(tx, row, product, customer, at); } if (row.orderId && ["in_progress", "completed", "cancelled"].includes(targetStatus!)) { const orderStatus = targetStatus === "in_progress" ? "preparing" : targetStatus; await tx.update(orders).set({ status: orderStatus!, updatedAt: at }).where(eq(orders.id, row.orderId)); if (targetStatus === "cancelled") { await tx.update(merchantPaymentAllocations).set({ settlementStatus: row.paymentStatus === "paid" ? "refund_required" : "cancelled", updatedAt: at }).where(eq(merchantPaymentAllocations.orderId, row.orderId)); const [linkedOrder] = await tx.select({ checkoutGroupId: orders.checkoutGroupId }).from(orders).where(eq(orders.id, row.orderId)).limit(1); if (linkedOrder?.checkoutGroupId) await tx.update(checkoutGroups).set({ status: row.paymentStatus === "paid" ? "refund_required" : "cancelled", paymentStatus: row.paymentStatus === "paid" ? "paid" : "cancelled", updatedAt: at }).where(eq(checkoutGroups.id, linkedOrder.checkoutGroupId)); } } await tx.insert(auditEvents).values({ actorRef: access.user.userId, action: `service_booking.${targetStatus}`, resourceType: "service_booking", resourceId: String(current.id), metadata: { previousStatus: current.status, scheduledStart: scheduledStart?.toISOString() ?? null, quotePrice: quoted ? quotePrice : null } }); return { ...row, status: targetStatus }; });
  if (!updated) return Response.json({ error: "This booking changed while you were editing it. Refresh and try again." }, { status: 409 });
  const [notice] = await db.select({ serviceName: products.name, storeName: merchants.name, customerName: users.displayName, customerEmail: users.email }).from(products).innerJoin(merchants, eq(merchants.id, products.merchantId)).innerJoin(users, eq(users.id, current.customerId)).where(eq(products.id, current.productId)).limit(1);
  if (notice) await sendBookingStatusNotification({ reference: `NCB-${String(current.id).padStart(6, "0")}`, ...notice, status: updated.status, requestedStart: updated.requestedStart, scheduledStart: updated.scheduledStart, durationMinutes: updated.durationMinutes, serviceMode: updated.serviceMode, price: updated.priceSnapshot, pricingModel: updated.pricingModel, note: updated.merchantNote }).catch((error) => console.error("booking status email failed", error));
  return Response.json({ booking: updated });
}
